### ISSUE TITLE
feature extractor code

### ISSUE THREAD

**Issue by oferidan1** [lck666666/HR-APR#1]
Hi,
Thanks for your great work!
Can you please share the code of the feature extractors you used (MS-Transformer, DFNet)?
Also, doing feature extraction for PoseNet model - it is by running feature_extractor/test.py?
Thanks,
Ofer

**Comment by lck666666** [comment]
Hi, sry for the late reply, to do the feature extraction for PoseNet model, you need to download cambridge landmarks/7scenes datasets and train a posenet (also a feature extractor) model. (see the updated readme)
```
cd ./feature_extractor
python test.py --image_path ./posenet/dataset/scene --metadata_path ./posenet/dataset/scene/dataset_test.txt --model Efficientnet
```
then, the feature descriptors are stored in ```.npy``` format as shown in the line 318 of ```./feature_extractor/solver.py```
